- src/types/gameConsole.ts
Wrong platform name for Odyssey 2 in the Analogue Pocket file structure.
> Fix: Magnavox Odyssey 2 {pocket} token

- package-lock.json
- package.json
- src/console/progressBarCLI.ts
- src/modules/argumentsParser.ts
- src/polyfill/consolePoly.ts
Temporarily addresses https://github.com/npkgz/cli-progress/issues/142
> Fix: manually wrap log lines

- src/types/logiqx/dat.ts
- src/types/logiqx/machine.ts
- test/fixtures/dats/patchable.dat
> Feature: support MAME XML DATs

- src/igir.ts
- src/modules/reportGenerator.ts
- src/modules/statusGenerator.ts
- src/types/datStatus.ts
- test/modules/reportGenerator.test.ts
- test/modules/statusGenerator.test.ts
> Fix: reporting on games with no ROMs

- src/modules/argumentsParser.ts
- src/types/logiqx/game.ts
- src/types/options.ts
- test/types/options.test.ts
> Feature: {gameType} output token

- src/console/singleBarFormatted.ts
> Fix: progress bar can't have negative "in progress" value

- .husky/pre-commit
Removes the use of double brackets, which is not compatible with all shell implementations.
> Git: update Husky pre-commit for POSIX sh Compatibility

- docs/output/tokens.md
- src/modules/argumentsParser.ts
- src/modules/candidateWriter.ts
- src/types/dats/release.ts
- src/types/internationalization.ts
- src/types/outputFactory.ts
- test/outputFactory.test.ts
Fixes: https://github.com/emmercm/igir/issues/696
> Feature: {gameRegion} and {gameLanguage} tokens

- src/modules/datParentInferrer.ts
- test/modules/datParentInferrer.test.ts
Fixes: https://github.com/emmercm/igir/issues/720
> Fix: don't infer parents for DATs that already have parent/clone info

- jest.config.ts
- package-lock.json
- package.json
- src/modules/datMergerSplitter.ts
- src/types/dats/rom.ts
- test/modules/datMergerSplitter.test.ts
Fixes https://github.com/emmercm/igir/issues/724
> Fix: ignore status:nodump ROMs when merging & splitting

- src/@types/robloachDatfile.d.ts
- src/modules/datScanner.ts
Fixes: https://github.com/emmercm/igir/issues/781
> Fix: catch CMPro DAT parsing errors

- docs/output/tokens.md
- docs/usage/handheld/miyoocfw.md
- mkdocs.yml
- src/modules/argumentsParser.ts
- src/types/gameConsole.ts
- src/types/outputFactory.ts
- test/outputFactory.test.ts
I want to add sorting support for [MiyooCFW](https://github.com/TriForceX/MiyooCFW/wiki/)
it can be used on the compact handheld firmware for some Bittboy, powkiddy (V/Q 20/90) and PocketGo devices. Work in progress.
I messed up the branch in my previous pull request. I am very sorry, if this wasted any resources, please let me make it up with a donation to the project. 
This is a draft based on the main before merge of PR#804. If that one gets merged I will rebase, if not I will submit this as is.
> Feature: output token {miyoocfw} for Bittboy/Powkiddy custom firmware MiyooCFW

- src/types/patches/bpsPatch.ts
Fixes https://github.com/emmercm/igir/issues/806
> Fix: BPS patch TARGET_COPY reading

- src/types/files/archives/zip.ts
> Fix: handle stream errors when reading a zip file

- src/polyfill/streamPoly.ts
- src/types/files/archives/zip.ts
- src/types/files/file.ts
- src/types/files/fileChecksums.ts
> Fix: don't leave open file handles when hashing zip entries

- src/modules/argumentsParser.ts
> Docs: update example use cases

- docs/roms/filtering-preferences.md
- src/modules/argumentsParser.ts
- src/modules/candidatePreferer.ts
- src/types/options.ts
- test/modules/argumentsParser.test.ts
- test/modules/candidatePreferer.test.ts
> Feature: prefer-game-regex, prefer-rom-regex options

- src/console/progressBar.ts
- src/igir.ts
- src/modules/argumentsParser.ts
- src/modules/candidateCombiner.ts
- src/modules/candidateGenerator.ts
- src/modules/candidateMergeSplitValidator.ts
- src/modules/candidatePatchGenerator.ts
- src/modules/candidatePostProcessor.ts
- src/modules/candidatePreferer.ts
- src/modules/candidateWriter.ts
- src/modules/datCombiner.ts
- src/modules/datFilter.ts
- src/modules/datGameInferrer.ts
- src/modules/datMergerSplitter.ts
- src/modules/datParentInferrer.ts
- src/modules/datScanner.ts
- src/modules/dir2DatCreator.ts
- src/modules/directoryCleaner.ts
- src/modules/fileIndexer.ts
- src/modules/fixdatCreator.ts
- src/modules/movedRomDeleter.ts
- src/modules/patchScanner.ts
- src/modules/reportGenerator.ts
- src/modules/romHeaderProcessor.ts
- src/modules/romScanner.ts
- src/modules/statusGenerator.ts
Fixes: https://github.com/emmercm/igir/issues/938
> Refactor: update log levels

- src/modules/directoryCleaner.ts
Hello again!
Based on my comment on the closed issue [here](https://github.com/emmercm/igir/issues/938#issuecomment-1960482147), I think that clean dry run should match the regular clean in terms of logging (on line 90). All of the other logs and their levels are great, just this clean dry run didn't match up.
Thank you!
> Fix: Update clean dry run to use info logging instead of debug

- package.ts
RE: https://github.com/emmercm/igir/issues/1084
> Fix: use node.exe for the caxa command on Windows

- src/polyfill/fsPoly.ts
- test/polyfill/filePoly.test.ts
RE: https://github.com/emmercm/igir/pull/1087
> Fix: revert FsPoly.copyDir() changes

- src/igir.ts
- src/modules/argumentsParser.ts
- src/types/files/fileCache.ts
- src/types/options.ts
- test/modules/argumentsParser.test.ts
Fixes: https://github.com/emmercm/igir/issues/1060
> Feature: cache path option

- src/types/dats/rom.ts
- test/fixtures/dats/headered.dat
- test/fixtures/dats/headerless.dat
- test/fixtures/dats/one.dat
> Fix: lowercase DAT ROM checksums

- src/constants.ts
- src/igir.ts
- src/modules/argumentsParser.ts
- src/polyfill/fsPoly.ts
> Fix: don't test default cache paths when one provided

- src/types/options.ts
RE: https://github.com/emmercm/igir/pull/1124
> Fix: sanitize non-glob paths when globbing

- index.ts
- package.ts
- src/igir.ts
- src/modules/argumentsParser.ts
- src/polyfill/fsPoly.ts
- src/types/dats/cmpro/cmProParser.ts
- src/types/expectedError.ts
- src/types/files/archives/rar.ts
- src/types/files/archives/sevenZip.ts
- src/types/files/archives/tar.ts
- src/types/files/archives/zip.ts
- src/types/files/fileFactory.ts
- src/types/options.ts
- src/types/outputFactory.ts
- src/types/patches/apsGbaPatch.ts
- src/types/patches/apsN64Patch.ts
- src/types/patches/bpsPatch.ts
- src/types/patches/dpsPatch.ts
- src/types/patches/ipsPatch.ts
- src/types/patches/ninjaPatch.ts
- src/types/patches/patch.ts
- src/types/patches/ppfPatch.ts
- src/types/patches/upsPatch.ts
- src/types/patches/vcdiffPatch.ts
RE: https://github.com/emmercm/igir/issues/1199
> Refactor: don't log the stack trace of expected errors

- src/modules/datParentInferrer.ts
- test/modules/datParentInferrer.test.ts
- test/types/dats/game.test.ts
RE: https://github.com/emmercm/igir/issues/1201
> Feature: handle No-Intro PS3 BIOS parent/clone inference

- src/modules/datScanner.ts
- src/types/dats/cmpro/cmProParser.ts
Fixes: https://github.com/emmercm/igir/issues/1204
> Fix: libretro System.dat BIOS assumption

- src/igir.ts
- src/modules/dir2DatCreator.ts
- src/types/dats/rom.ts
- test/modules/dir2DatCreator.test.ts
RE: https://github.com/emmercm/igir/pull/1174
> Refactor: dir2dat use Game and ROM information from candidates

- docs/output/cleaning.md
- src/modules/argumentsParser.ts
- src/modules/directoryCleaner.ts
- src/types/options.ts
- test/modules/argumentsParser.test.ts
- test/modules/directoryCleaner.test.ts
Fixes: https://github.com/emmercm/igir/issues/1069
> Feature: cleaning backup directory option

- src/modules/datScanner.ts
- src/types/cache.ts
- src/types/files/archives/gzip.ts
- src/types/options.ts
- test/igir.test.ts
- test/modules/argumentsParser.test.ts
- test/modules/candidateWriter.test.ts
- test/modules/datGameInferrer.test.ts
- test/modules/datScanner.test.ts
- test/modules/patchScanner.test.ts
- test/modules/romScanner.test.ts
Fixes: https://github.com/emmercm/igir/issues/1199
> Fix: don't throw if a single dat/input/patch directory is empty

- src/console/progressBar.ts
- src/modules/candidateExtensionCorrector.ts
- src/types/cache.ts
- src/types/files/fileCache.ts
- src/types/files/fileFactory.ts
- src/types/files/fileSignature.ts
- src/types/files/romHeader.ts
Fixes: https://github.com/emmercm/igir/issues/1234
> Feature: cache file signature detection

- src/modules/datScanner.ts
- src/polyfill/urlPoly.ts
- src/types/files/archives/archive.ts
- src/types/files/file.ts
- src/types/files/fileFactory.ts
Fixes: https://github.com/emmercm/igir/issues/1275
> Fix: downloading & extracting temp files

- src/types/files/archives/archiveEntry.ts
RE: https://github.com/emmercm/igir/pull/1229
> Fix: don't CRC32 checksum files by default

- src/globals/defaults.ts
- src/modules/dats/datScanner.ts
- src/modules/directoryCleaner.ts
- src/modules/movedRomDeleter.ts
- src/modules/roms/romHeaderProcessor.ts
- src/polyfill/fsPoly.ts
- src/types/files/archives/chd/chdGdiParser.ts
- src/types/files/fileCache.ts
RE: https://github.com/emmercm/igir/issues/1408
> Fix: limit to MAX_FS_THREADS in more places

- src/types/files/archives/zip.ts
- test/types/files/archives/archive.test.ts
- test/types/files/archives/archiveEntry.test.ts
Fixes: https://github.com/emmercm/igir/issues/1399
> Fix: prevent hanging forever on non-DEFLATE zips

- docs/roms/filtering-preferences.md
- src/types/dats/game.ts
- test/types/dats/game.test.ts
Fixes: https://github.com/emmercm/igir/issues/1342
> Fix: treat SNES enhancement chips as non-retail

- .github/renovate.json5
- .github/workflows/gh-pages.yml
> Fix: Revert "Chore: pin dependency python to 3.4.10"

- src/polyfill/fsPoly.ts
EXDEV errors were not handled because the other error check matched before
> Fix: check for EXDEV error before other errors

- src/modules/argumentsParser.ts
- test/modules/argumentsParser.test.ts
RE: https://github.com/emmercm/igir/issues/1807
> Fix: don't allow patch options to be used with link command
