emmercm/igir

- src/console/progressBar.ts
- src/console/progressBarCLI.ts
- src/modules/romWriter.ts
- test/console/progressBarFake.ts
> Fix: allow multiple pending progress bar waiting messages

- src/modules/argumentsParser.ts
- src/modules/datScanner.ts
- src/types/options.ts
- test/modules/argumentsParser.test.ts
- test/modules/datScanner.test.ts
- test/modules/outputCleaner.test.ts
- test/modules/patchScanner.test.ts
- test/modules/romScanner.test.ts
- test/modules/romWriter.test.ts
- test/types/logiqx/dat.test.ts
- test/types/logiqx/game.test.ts
- test/types/releaseCandidate.test.ts
> Feature: DAT filtering options

- src/modules/argumentsParser.ts
- src/modules/candidateGenerator.ts
- src/modules/headerProcessor.ts
- src/types/options.ts
- test/modules/argumentsParser.test.ts
- test/modules/headerProcessor.test.ts
> Fix: require extract or zip commands for ROM header manipulation

- docs/advanced-examples.md
- src/modules/candidateGenerator.ts
> Refactor: reduce log level for output file exceptions

- src/console/logger.ts
- src/igir.ts
- src/modules/outputCleaner.ts
- src/modules/reportGenerator.ts
- src/modules/romWriter.ts
- src/types/datStatus.ts
- test/modules/reportGenerator.test.ts
> Feature: report what files were cleaned

- src/modules/argumentsParser.ts
- src/modules/romWriter.ts
- src/types/options.ts
- test/modules/argumentsParser.test.ts
- test/modules/romWriter.test.ts
> Feature: overwrite "invalid" CLI flag

- test/types/files/archives/archive.test.ts
- test/types/files/archives/archiveEntry.test.ts
- test/types/files/archives/zip.test.ts
> Test: for graceful handling of zipping non-existent files

- README.md
- docs/file-scanning.md
> Docs: file scanning

- docs/reporting.md
- src/console/logger.ts
- src/modules/argumentsParser.ts
- src/modules/reportGenerator.ts
- src/types/options.ts
- test/igir.test.ts
- test/modules/argumentsParser.test.ts
- test/modules/reportGenerator.test.ts
> Feature: report output path option

- src/console/progressBar.ts
- src/igir.ts
- src/modules/romWriter.ts
- test/igir.test.ts
> Fix: delay deleting moved files until after all writing has finished

- index.ts
- package.json
- src/constants.ts
- src/igir.ts
> Fix: enforce required Node.js version

- src/igir.ts
- src/modules/movedRomDeleter.ts
- test/igir.test.ts
- test/modules/movedRomDeleter.test.ts
> Fix: when moving, don't delete archives unless every file entry is matched

- README.md
- docs/examples.md
- docs/installation.md
- docs/reporting.md
- package.json
- src/modules/argumentsParser.ts
- src/types/gameConsole.ts
- src/types/options.ts
- test/types/options.test.ts
> Feature: {onion} output token

- src/console/progressBarCLI.ts
- src/elasticSemaphore.ts
- src/modules/romWriter.ts
> Fix: don't ever shrink a semaphore's value

- src/modules/headerProcessor.ts
- src/types/files/archives/sevenZip.ts
- src/types/files/archives/zip.ts
> Fix: bandaid 7zip-min not enumerating unicdoe filenames on Windows

- src/console/singleBarFormatted.ts
- test/modules/fixdatCreator.test.ts
> Fix: scale progress bar in-progress correctly

- index.ts
- src/console/progressBarCLI.ts
- src/console/singleBarFormatted.ts
- src/igir.ts
- test/console/progressBarCLI.test.ts
> Fix: make non-TTY output consistent with progress bar freezing

- CONTRIBUTING.md
> Fix: remove empty contribution guidelines

- src/types/gameConsole.ts
Fixes https://github.com/emmercm/igir/issues/576
> Feature: add Xbox and Xbox 360 support for {batocera}

- src/polyfill/fsPoly.ts
- src/types/datStatus.ts
Fixes https://github.com/emmercm/igir/pull/636
> Refactor: use the nullish operator where possible

- src/igir.ts
- src/modules/movedRomDeleter.ts
- test/igir.test.ts
- test/modules/movedRomDeleter.test.ts
> Fix: don't clean fixdats

- src/types/dats/game.ts
- test/outputFactory.test.ts
Fixes https://github.com/emmercm/igir/issues/689
> Fix: don't assume games with releases are "verified"

- src/modules/datMergerSplitter.ts
- test/modules/datMergerSplitter.test.ts
Fixes https://github.com/emmercm/igir/issues/691
> Fix: de-duplicate split/merged ROM sets

- src/modules/datMergerSplitter.ts
- src/types/outputFactory.ts
- test/modules/datMergerSplitter.test.ts
- test/outputFactory.test.ts
Fixes https://github.com/emmercm/igir/issues/695
> Fix: respect output archive entry paths with subdirectories

- src/modules/datMergerSplitter.ts
- test/modules/datMergerSplitter.test.ts
Fixes https://github.com/emmercm/igir/issues/717
> Fix: merging parent/clone with same ROM filename and different checksum

- src/modules/datMergerSplitter.ts
- src/types/dats/game.ts
- test/modules/datMergerSplitter.test.ts
Related to https://github.com/emmercm/igir/issues/724
> Fix: only exclude BIOS ROMs found in referenced romOf game

- src/modules/candidateWriter.ts
- src/modules/datMergerSplitter.ts
- src/modules/movedRomDeleter.ts
- src/polyfill/arrayPoly.ts
Fixes https://github.com/emmercm/igir/issues/724
> Refactor: filter to unique array values, comparing mapped values

- src/modules/candidatePreferer.ts
- test/modules/candidatePreferer.test.ts
Fixes https://github.com/emmercm/igir/issues/726
> Fix: better 1G1R preference of games that share a primary language

- package-lock.json
- package.json
- src/modules/datScanner.ts
- src/types/dats/cmpro/cmProParser.ts
RE: https://github.com/emmercm/igir/issues/781
> Fix: replace robloach-datfile with a custom CMPro DAT parser

- .husky/pre-commit
- package.json
- scripts/update-readme-help.sh
Fixes https://github.com/emmercm/igir/pull/787
> Fix: provide ts-node as a loader to the start script

- src/modules/argumentsParser.ts
- src/types/gameConsole.ts
- test/outputFactory.test.ts
During the last Pull request, I overlooked some issues that I tried to rectify in this one:
* Mainly documentation issues
* Remove mapping for NeoGeo because it is not supported
Sorry for the confusion
> Fix: Fix some issues with output token funkeyos

- docs/output/tokens.md
- docs/usage/handheld/jelos.md
- mkdocs.yml
closes: #743 
Add documentation for the JELOS output token
Also add the documentation for FunKey OS to the nav.
> Docs: JELOS output token

- src/modules/datScanner.ts
- test/fixtures/dats/one.dat
- test/modules/datScanner.test.ts
Fxies https://github.com/emmercm/igir/issues/822
> Fix: exclude zero size ROMs

- docs/input/reading-archives.md
- mkdocs.yml
- src/types/files/archives/tar.ts
- src/types/files/archives/zip.ts
- src/types/files/fileChecksums.ts
- test/types/files/archives/archiveEntry.test.ts
Fixes https://github.com/emmercm/igir/issues/819
> Fix: eliminate TAR extraction temp files, reduce ZIP checksum file reads

- src/driveSemaphore.ts
- src/modules/fileIndexer.ts
- src/polyfill/fsPoly.ts
- test/polyfill/fsPoly.test.ts
Fixes: https://github.com/emmercm/igir/issues/856
> Fix: only query disk info at startup

- src/modules/candidateGenerator.ts
- test/modules/candidateGenerator.test.ts
> Fix: clearer conflicting input files log message

- docs/roms/filtering-preferences.md
- src/modules/argumentsParser.ts
- src/modules/datFilter.ts
- src/modules/datScanner.ts
- src/types/options.ts
- test/modules/argumentsParser.test.ts
Fixes: https://github.com/emmercm/igir/issues/655
> Feature: support reading regex patterns from files

- src/igir.ts
- src/modules/argumentsParser.ts
- src/modules/datParentInferrer.ts
- src/types/options.ts
- test/modules/argumentsParser.test.ts
- test/modules/datParentInferrer.test.ts
RE: https://github.com/emmercm/igir/issues/754
> Feature: dat-ignore-parent-clone option

- package.json
- scripts/update-readme-help.sh
> Fix: reduce README help message width for GitHub

- src/constants.ts
> Fix: greatly reduce the number of allowed filesystem threads

- src/modules/candidateCombiner.ts
- src/modules/candidatePatchGenerator.ts
- src/types/dats/dat.ts
- src/types/dats/parent.ts
- test/modules/candidatePostProcessor.test.ts
- test/modules/candidatePreferer.test.ts
- test/modules/fixdatCreator.test.ts
- test/modules/reportGenerator.test.ts
- test/modules/statusGenerator.test.ts
> Refactor: eliminate unnecessary game name storage

- src/types/dats/game.ts
- test/modules/datMergerSplitter.test.ts
> Refactor: remove some unused game properties

- package-lock.json
- package.json
- src/modules/datScanner.ts
- src/types/dats/dat.ts
- src/types/dats/datObject.ts
- test/modules/candidateWriter.test.ts
- test/types/dats/logiqx/logiqxDat.test.ts
- test/types/dats/mame/mameDat.test.ts
> Refactor: replace xml2js with fast-xml-parser

- src/types/files/archives/archiveEntry.ts
- src/types/files/file.ts
- test/types/files/archives/archiveEntry.test.ts
- test/types/files/file.test.ts
> Feature: ability to calculate headerless MD5 & SHA1

- src/modules/candidateWriter.ts
- src/modules/scanner.ts
- src/polyfill/filePoly.ts
- src/polyfill/fsPoly.ts
- src/types/files/file.ts
- test/modules/romScanner.test.ts
- test/polyfill/fsPoly.test.ts
- test/types/files/archives/archiveEntry.test.ts
- test/types/files/file.test.ts
Fixes: https://github.com/emmercm/igir/issues/939
> Fix: ability to scan directory symbolic links

- docs/advanced/internals.md
- docs/advanced/logging.md
- docs/commands.md
- docs/dats/fixdats.md
- docs/output/cleaning.md
- src/igir.ts
- src/modules/argumentsParser.ts
- src/modules/candidateWriter.ts
- src/polyfill/fsPoly.ts
- src/types/options.ts
- test/igir.test.ts
- test/modules/argumentsParser.test.ts
- test/modules/candidateWriter.test.ts
- test/modules/directoryCleaner.test.ts
- test/modules/romScanner.test.ts
- test/polyfill/fsPoly.test.ts
- test/types/files/archives/archiveEntry.test.ts
- test/types/files/file.test.ts
Fixes: https://github.com/emmercm/igir/issues/942
> Feature: hard link support

- package.json
- src/modules/datFilter.ts
- test/modules/datFilter.test.ts
> Fix: don't orphan children when filtering out parents

- src/modules/datFilter.ts
- test/modules/datFilter.test.ts
> Fix: games can't be both a parent and clone

- src/types/gameConsole.ts
Added newly supported Onion systems: https://onionui.github.io/docs/emulators
> Fix: Added Newly Supported Onion Game Systems (NDS, etc)

- src/types/gameConsole.ts
- test/outputFactory.test.ts
Fixes: https://github.com/emmercm/igir/issues/1043
> Fix: Famicom and Super Famicom output token matching

- src/modules/datParentInferrer.ts
- test/modules/datParentInferrer.test.ts
> Fix: treat GoodTools alternates as clones

- docs/roms/filtering-preferences.md
- src/modules/datParentInferrer.ts
- src/types/dats/game.ts
- test/types/dats/game.test.ts
> Feature: detect "cracked" games, treat as non-retail

- src/constants.ts
- src/polyfill/fsPoly.ts
- src/types/cache.ts
- test/types/cache.test.ts
> Fix: make sure the cache file is writable

- src/polyfill/fsPoly.ts
RE: https://github.com/emmercm/igir/pull/1086
> Fix: update copied file permissions with 0o222

- src/modules/argumentsParser.ts
- test/modules/argumentsParser.test.ts
RE: https://github.com/emmercm/igir/issues/1111
> Feature: validate language and region option values

- src/modules/datParentInferrer.ts
- test/modules/datParentInferrer.test.ts
RE: https://github.com/emmercm/igir/issues/1111
> Feature: infer abbreviated years in game names

- src/modules/argumentsParser.ts
- src/modules/candidateGenerator.ts
- src/modules/reportGenerator.ts
- src/types/options.ts
- test/modules/argumentsParser.test.ts
- test/modules/candidateGenerator.test.ts
Fixes: https://github.com/emmercm/igir/issues/1111
> Feature: allow reporting with no input when not writing ROMs

- src/types/datStatus.ts
- test/modules/statusGenerator.test.ts
RE: https://github.com/emmercm/igir/issues/1111
> Fix: report non-preferred games as IGNORED when no game found

- src/modules/datScanner.ts
- src/types/dats/game.ts
- src/types/outputFactory.ts
- test/outputFactory.test.ts
Fixes: https://github.com/emmercm/igir/issues/1136
> Feature: add {genre} token

- src/types/files/file.ts
Fixes: https://github.com/emmercm/igir/issues/1195
> Fix: mkdir before downloading DATs

- src/modules/fixdatCreator.ts
- src/types/options.ts
- src/types/outputFactory.ts
Fixes: https://github.com/emmercm/igir/issues/1200
> Fix: write fixdats to the output dir root

- src/modules/datCombiner.ts
- test/modules/datCombiner.test.ts
RE: https://github.com/emmercm/igir/pull/1208
> Fix: remove duplicate games when combining DATs

- package-lock.json
- package.json
- src/types/files/archives/zip.ts
Fixes: https://github.com/emmercm/igir/issues/991
> Fix: ZJONSSON/node-unzipper#324

- src/modules/romHeaderProcessor.ts
- src/types/files/archives/archiveEntry.ts
- src/types/files/file.ts
- src/types/files/fileCache.ts
- src/types/files/fileFactory.ts
- src/types/files/romHeader.ts
- test/types/files/archives/archiveEntry.test.ts
- test/types/files/file.test.ts
- test/types/files/fileCache.test.ts
- test/types/files/romHeader.test.ts
RE: https://github.com/emmercm/igir/issues/1234
> Feature: cache ROM header detection

- .github/workflows/gh-pages.yml
- docs/output/cleaning.md
- docs/roms/filtering-preferences.md
- docs/usage/best-practices.md
RE: https://github.com/emmercm/igir/issues/1337
> Docs: update

- src/types/files/archives/sevenZip/sevenZip.ts
RE: https://github.com/emmercm/igir/pull/1421
> Fix: add 7zip error string formatting back

- .github/workflows/node-test.yml
- docs/input/reading-archives.md
RE: https://github.com/emmercm/igir/issues/1398
> CI: test macOS without installing SDL2

- src/modules/dats/datScanner.ts
- src/modules/patchScanner.ts
- src/modules/scanner.ts
Fixes: https://github.com/emmercm/igir/issues/1368
> Fix: calculate checksums for files that are de-duplicated

- .github/workflows/node-branch-exec.yml
- .github/workflows/node-compile.yml
- .github/workflows/node-test.yml
- test/endToEndTest.sh
RE: https://github.com/emmercm/igir/pull/1439
> CI: don't test on Intel macOS

- src/modules/dats/datScanner.ts
- src/types/files/file.ts
Fixes: https://github.com/emmercm/igir/issues/1465
> Fix: don't de-duplicate URL files

- src/polyfill/fsPoly.ts
Fixes: https://github.com/emmercm/igir/issues/1479
> Fix: moving files across drives

- src/polyfill/fsPoly.ts
Fixes: https://github.com/emmercm/igir/issues/1478
> Fix: silently ignore node-disk-info failure

- docs/roms/filtering-preferences.md
- src/types/dats/game.ts
- test/types/dats/game.test.ts
Fixes: https://github.com/emmercm/igir/issues/1349
> Feature: consider MAME bootlegs and hacks as non-retail

- docs/roms/filtering-preferences.md
- src/modules/argumentsParser.ts
- src/modules/dats/datFilter.ts
- src/modules/dats/datScanner.ts
- src/types/dats/cmpro/cmProParser.ts
- src/types/dats/game.ts
- src/types/dats/logiqx/logiqxDat.ts
- src/types/dats/mame/machine.ts
- src/types/dats/mame/mameDat.ts
- src/types/dats/softwarelist/dataArea.ts
- src/types/dats/softwarelist/part.ts
- src/types/dats/softwarelist/software.ts
- src/types/dats/softwarelist/softwareListDat.ts
- src/types/dats/softwarelist/softwareListsDat.ts
- src/types/options.ts
- test/modules/argumentsParser.test.ts
- test/modules/dats/datFilter.test.ts
Fixes: https://github.com/emmercm/igir/issues/1389
> Feature: game category filter

- src/igir.ts
- src/modules/candidates/candidateArchiveFileHasher.ts
- src/modules/candidates/candidateCombiner.ts
- src/modules/candidates/candidateExtensionCorrector.ts
- src/modules/candidates/candidateGenerator.ts
- src/modules/candidates/candidateMergeSplitValidator.ts
- src/modules/candidates/candidatePatchGenerator.ts
- src/modules/candidates/candidatePostProcessor.ts
- src/modules/candidates/candidateValidator.ts
- src/modules/candidates/candidateWriter.ts
- src/modules/dats/datFilter.ts
- src/modules/dats/datMergerSplitter.ts
- src/modules/dats/datParentInferrer.ts
- src/modules/dats/datPreferer.ts
- src/modules/dats/datScanner.ts
- src/modules/dir2DatCreator.ts
- src/modules/fixdatCreator.ts
- src/modules/statusGenerator.ts
- src/types/datStatus.ts
- src/types/dats/dat.ts
- src/types/outputFactory.ts
Fixes: https://github.com/emmercm/igir/issues/1412
> Refactor: breaking: don't manipulate DAT names

- src/types/dats/game.ts
- test/modules/dats/datPreferer.test.ts
- test/types/dats/game.test.ts
Fixes: https://github.com/emmercm/igir/discussions/1496
> Fix: prefer region information in game names

- docs/advanced/internals.md
- docs/roms/sets.md
- mkdocs.yml
- src/igir.ts
- src/modules/argumentsParser.ts
- src/modules/dats/datDiscMerger.ts
- src/modules/dats/datParentInferrer.ts
- src/types/options.ts
- test/modules/argumentsParser.test.ts
- test/modules/dats/datDiscMerger.test.ts
RE: https://github.com/emmercm/igir/issues/587
> Feature: merge discs option

- src/modules/candidates/candidateWriter.ts
Fixes: https://github.com/emmercm/igir/issues/1537
> Fix: symlink absolute paths

- .github/renovate.json5
RE: https://github.com/emmercm/igir/issues/1581
> CI: keep Node.js up to date with 'current'

- src/gameGrouper.ts
- src/modules/dats/datScanner.ts
- test/modules/dats/datScanner.test.ts
Fixes: https://github.com/emmercm/igir/issues/1554
> Fix: group multi-ROM HTGD SMDB games

- src/modules/dats/datParentInferrer.ts
- src/types/dats/dat.ts
Fixes: https://github.com/emmercm/igir/issues/1570
> Fix: parent/clone inference with id/cloneofid-based DATs

- src/driveSemaphore.ts
- src/igir.ts
- src/keyedMutex.ts
- src/modules/candidates/candidateExtensionCorrector.ts
- src/modules/candidates/candidateGenerator.ts
- src/modules/candidates/candidateWriter.ts
- test/modules/candidates/candidateCombiner.test.ts
- test/modules/candidates/candidateExtensionCorrector.test.ts
- test/modules/candidates/candidateGenerator.test.ts
- test/modules/candidates/candidatePatchGenerator.test.ts
- test/modules/candidates/candidateWriter.test.ts
- test/modules/dir2DatCreator.test.ts
- test/modules/movedRomDeleter.test.ts
Fixes: https://github.com/emmercm/igir/issues/1565
> Feature: warn when writing to the same output file path

- .github/renovate.json5
> CI: Renovate rollback npm constraint failures (revert)

- .github/renovate.json5
RE: https://github.com/emmercm/igir/issues/1698
> CI: fix: Renovate constraints filtering dependency types

- docs/misc/rom-dumping.md
- docs/misc/torrentzip.md
- packages/torrentzip/test/tzWriter.test.ts
Fixes: https://github.com/emmercm/igir/issues/1755
> CI: test zipping empty directories

- src/igir.ts
- src/modules/candidates/candidateGenerator.ts
- src/modules/candidates/candidatePatchGenerator.ts
- src/modules/candidates/candidateWriter.ts
- src/modules/patchScanner.ts
- src/modules/scanner.ts
- test/modules/candidates/candidateWriter.test.ts
Fixes: https://github.com/emmercm/igir/issues/1792
> Fix: don't consider zips for raw-moving when patching

- .gitignore
- src/types/dats/logiqx/logiqxDat.ts
- src/types/dats/mame/mameDat.ts
- test/igir.test.ts
- test/modules/dats/datScanner.test.ts
Fixes: https://github.com/emmercm/igir/issues/1790
> Fix: parse libretro mame2003 DATs
